import streamlit as st
from src import router_workflow

AGENT_EMOJIS = {
    "calendar_manager": "📅",  # Calendar emoji
    "email_manager": "📧",  # Email emoji
    "health_coach": "🏋️",  # Fitness emoji
    "life_advisor": "🌟",  # Star emoji (for motivation)
}


def main():
    st.set_page_config(page_title="AI Assistant", page_icon="🤖", layout="centered")

    st.title("🤖 AI Assistant")
    st.subheader("Powered by LangGraph & Google Gemini API")
    st.markdown(
        "This intelligent assistant routes your queries to the most relevant AI agent based on the context. "
        "It includes four specialized agents:"
    )

    # Display agent descriptions with emojis
    st.markdown(
        """
    - 📅 **Calendar Manager**: Helps manage your appointments.
    - 📧 **Email Manager**: Assists with drafting emails.
    - 🏋️ **Health Coach**: Provides fitness and wellness guidance.
    - ⭐ **Life Advisor**: Offers motivation and life advice.
    """
    )

    st.divider()

    # User input
    user_input = st.text_area(
        "✍️ Enter your query:",
        "What’s one thing I can do right now to get closer to my dream?",
    )

    if st.button("✨ Generate Response"):
        if user_input.strip():
            # Invoke the workflow
            state = router_workflow.invoke({"input": user_input})
            agent_used = state.get("agent", "Unknown")

            # Display response
            st.subheader("💡 Response:")
            st.write(state.get("output", "No response generated."))

            # Display agent responsible for response
            if agent_used in AGENT_EMOJIS:
                st.success(
                    f"This response was generated by {AGENT_EMOJIS[agent_used]} **{agent_used.replace('_', ' ').title()}**"
                )
        else:
            st.warning("⚠️ Please enter a valid query.")


if __name__ == "__main__":
    main()
